services:
  - type: web
    name: course-recommendation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DISABLE_POETRY
        value: true
